rvm:
  - 1.8.7
  - 1.9.2
  - 1.9.3
  - 2.0.0
  - 2.1.0
  - 2.2.0
  - rbx-2
  - ree
  - jruby-18mode
  - jruby-19mode
matrix:
  allow_failures:
    - rvm: jruby-18mode
    - rvm: jruby-19mode
before_install:
  - sudo apt-get update -qq
  - sudo apt-get install -y postgresql-server-dev-all
